name: Publish to PyPI

on:
  workflow_run:
    workflows: ["Build Python Wheels"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      confirm:
        description: "Are you sure you want to publish to PyPI?"
        type: boolean
        required: true
        default: false

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.confirm == true) ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    environment: pypi
    permissions:
      id-token: write

    steps:
      - name: Download all wheel artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-wheels.yml
          workflow_conclusion: success
          path: dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
          if_no_artifact_found: error

      - name: Prepare wheels for upload
        run: |
          mkdir -p wheels
          find dist -name "*.whl" -exec cp {} wheels/ \;

      - name: Verify wheels
        run: |
          echo "Found wheel files:"
          ls -l wheels/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: wheels/
          skip-existing: true
          verbose: true
