name: Publish to PyPI

on:
  workflow_run:
    workflows: ["Build Python Wheels"]
    types:
      - completed

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: pypi
    permissions:
      id-token: write

    steps:
      - name: Download all wheel artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist

      - name: Prepare wheels for upload
        run: |
          mkdir -p wheels
          find dist -name "*.whl" -exec cp {} wheels/ \;

      - name: Verify wheels
        run: |
          echo "Found wheel files:"
          ls -l wheels/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: wheels/
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
          verbose: true
